### ISSUE TITLE
[META] 1.0 Checklist

### ISSUE THREAD

**Issue by runspired** [runspired/smoke-and-mirrors#161]
- [ ] Release [@html-next/vertical-collection 1.0](https://github.com/html-next/vertical-collection)
- [ ] Make smoke-and-mirrors install and manage vertical-collection similar to how we did with [@html-next/flexi](https://github.com/html-next/flexi)
  - this will close #70 #85 #95 #116 #124 #125 #127 #145 #150 #158 
- [ ] Remove the vertical-collection implementation here
- [ ] Upgrade `occludable-area` and others to use the improved radar in `vertical-collection`
- [ ] move smoke-and-mirrors into the `@html-next` org (and ensure docs transition correctly)
- [ ] resolve #160 #159 
- [ ] resolve #62 (needs bikeshed on what should render when in fastboot mode)
- [ ] improve the CSS Debugger (and ensure it still works) within `vertical-collection` (resolve #59)

**Comment by runspired** [comment]
cc @pzuraq

**Comment by v3ss0n** [comment]
is #145 fixed in vertical-collection ?

**Comment by runspired** [comment]
@v3ss0n yes.
