### ISSUE TITLE
[META] Fastboot support

### ISSUE THREAD

**Issue by runspired** [runspired/smoke-and-mirrors#62]
This is a meta ticket for tracking fastboot support.

In fastboot mode:
- [ ] render everything
- [ ] provide scaffolded dimensions when needed
- [ ] Guard against DOM related APIs
  - [ ] `window`
  - [ ] `document`
  - [ ] `self`
  - [ ] `document.body`
  - [ ] `requestAnimationFrame`
  - [ ] `getBoundingClientRect`
  - [ ] `localStorage`
  - [ ] `document.createElement`
  - [ ] `element.append`
  - [ ] `addEventListener`/`removeEventListener`
  - [ ] anything related to `document.title` and similar (soon to be used by the `extended-router`)

**Comment by tschoartschi** [comment]
I wanted to ask about the status of this meta-issue. Is there work going on? Is the "help wanted" label still relevant?

**Comment by erkarl** [comment]
@tschoartschi - don't think it's been worked on. I've been meaning to allocate some time for this since this it's the only thing right now that's preventing me from running my app in production.
